security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:5000/.well-known/openid-configuration/jwks
      token-type: Bearer
      token-info-uri: http://localhost:5000/connect/token